module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: '<rootDir>/jest.global-setup.ts',
  collectCoverage: false,
  coverageReporters: ['json-summary', 'lcov', 'clover'],
  moduleNameMapper: {
    '^@osf/(.*)$': '<rootDir>/src/app/$1',
    '^@core/(.*)$': '<rootDir>/src/app/core/$1',
    '^@shared/(.*)$': '<rootDir>/src/app/shared/$1',
    '^@styles/(.*)$': '<rootDir>/assets/styles/$1',
    '^@testing/(.*)$': '<rootDir>/src/testing/$1',
    '^src/environments/environment$': '<rootDir>/src/environments/environment.ts',
    '^cedar-artifact-viewer$': '<rootDir>/src/testing/mocks/cedar-artifact-viewer.mock.ts',
    '^cedar-embeddable-editor$': '<rootDir>/src/testing/mocks/cedar-embeddable-editor.mock.ts',
  },
  transform: {
    '^.+\\.(ts|mjs|js|html)$': [
      'jest-preset-angular',
      {
        tsconfig: '<rootDir>/tsconfig.spec.json',
        stringifyContentPathRegex: '\\.(html|svg)$',
        useESM: true,
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$|@ngxs|@angular|@ngrx|parse5|entities|chart.js)'],
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['ts', 'js', 'html', 'json', 'mjs'],
  coverageDirectory: 'coverage',
  collectCoverageFrom: [
    'src/app/**/*.{ts,js}',
    '!src/app/core/theme/**',
    '!src/app/app.config.ts',
    '!src/app/app.routes.ts',
    '!src/app/**/*.routes.{ts,js}',
    '!src/app/**/**/*.routes.{ts,js}',
    '!src/app/**/*.route.{ts,js}',
    '!src/app/**/mappers/**',
    '!src/app/shared/mappers/**',
    '!src/app/**/*.models.{ts.js}',
    '!src/app/**/*.model.{ts.js}',
    '!src/app/**/models/*.{ts,js}',
    '!src/app/shared/models/**',
    '!src/app/**/*.enum.{ts,js}',
    '!src/app/**/*.type.{ts,js}',
    '!src/app/**/*.spec.{ts,js}',
    '!src/app/**/*.module.ts',
    '!src/app/**/index.ts',
    '!src/app/**/public-api.ts',
  ],
  extensionsToTreatAsEsm: ['.ts'],
  coverageThreshold: {
    global: {
      branches: 31.0,
      functions: 35.0,
      lines: 64.0,
      statements: 64.0,
    },
  },
  watchPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/',
    '<rootDir>/coverage/',
    '<rootDir>/src/assets/',
    '<rootDir>/src/environments/',
    '<rootDir>/src/@types/',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/src/environments',
    '<rootDir>/src/app/features/files/pages/file-detail',
    '<rootDir>/src/app/features/project/addons/',
    '<rootDir>/src/app/features/settings/addons/',
    '<rootDir>/src/app/features/settings/tokens/store/',
  ],
};
