export const environment = {
  production: false,
  webUrl: 'https://staging4.osf.io',
  downloadUrl: 'https://staging4.osf.io/download',
  apiUrl: 'https://api.staging4.osf.io/v2',
  apiUrlV1: 'https://staging4.osf.io/api/v1',
  apiDomainUrl: 'https://api.staging4.osf.io',
  shareDomainUrl: 'https://staging-share.osf.io/trove',
  addonsApiUrl: 'https://addons.staging4.osf.io/v1',
  fileApiUrl: 'https://files.us.staging4.osf.io/v1',
  funderApiUrl: 'https://api.crossref.org/',
  casUrl: 'https://accounts.staging4.osf.io',
  recaptchaSiteKey: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
  twitterHandle: 'OSFramework',
  facebookAppId: '1022273774556662',
  supportEmail: 'support@osf.io',
  defaultProvider: 'osf',
  dataciteTrackerRepoId: null,
  dataciteTrackerAddress: 'https://analytics.datacite.org/api/metric',
  google: {
    GOOGLE_FILE_PICKER_CLIENT_ID: '610901277352-m5krehjdtu8skh2teq85fb7mvk411qa6.apps.googleusercontent.com',
    GOOGLE_FILE_PICKER_API_KEY: 'AIzaSyA3EnD0pOv4v7sJt7BGuR1i2Gcj-Gju6C0',
    GOOGLE_FILE_PICKER_APP_ID: 610901277352,
  },
};
